spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/userDB?serverTimezone=Asia/Seoul
    username: ${DB_USER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  driver:
    path: chromedriver
  jwt:
    secret: ${JWT_KEY}
    token:
      access-expiration-time: 60000    # 1분
      refresh-expiration-time: 604800000   # 7일

  data:
    redis:
      host: localhost
      port: 6379